# https://gecgithub01.walmart.com/mobile-platform/github-app-monolith
enabled_features:
  - autolabeler
  - bot-pr-merge
  - semantic-pull-requests
  - stalebot
  - merge-queue
  - stale-branch-bot
  - sync-base-branch
  - non-optimistic-merge
  - non-optimistic-merge-queue
merge_user: Diksha Agarwal
add_pr_label: allowRetry
